# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.zak.codes:
    container_name: orderer.zak.codes
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/zak.codes/orderers/orderer.zak.codes/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/zak.codes/orderers/orderer.zak.codes/tls/:/var/hyperledger/orderer/tls
    - orderer.zak.codes:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.city1.zak.codes:
    container_name: peer0.city1.zak.codes
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.city1.zak.codes
      - CORE_PEER_ADDRESS=peer0.city1.zak.codes:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.city1.zak.codes:7051
      - CORE_PEER_LOCALMSPID=City1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/city1.zak.codes/peers/peer0.city1.zak.codes/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/city1.zak.codes/peers/peer0.city1.zak.codes/tls:/etc/hyperledger/fabric/tls
        - peer0.city1.zak.codes:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer1.city1.zak.codes:
    container_name: peer1.city1.zak.codes
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.city1.zak.codes
      - CORE_PEER_ADDRESS=peer1.city1.zak.codes:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.city1.zak.codes:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.city1.zak.codes:7051
      - CORE_PEER_LOCALMSPID=City1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/city1.zak.codes/peers/peer1.city1.zak.codes/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/city1.zak.codes/peers/peer1.city1.zak.codes/tls:/etc/hyperledger/fabric/tls
        - peer1.city1.zak.codes:/var/hyperledger/production

    ports:
      - 8051:7051
      - 8053:7053

  peer0.city2.zak.codes:
    container_name: peer0.city2.zak.codes
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.city2.zak.codes
      - CORE_PEER_ADDRESS=peer0.city2.zak.codes:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.city2.zak.codes:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.city2.zak.codes:7051
      - CORE_PEER_LOCALMSPID=City2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/city2.zak.codes/peers/peer0.city2.zak.codes/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/city2.zak.codes/peers/peer0.city2.zak.codes/tls:/etc/hyperledger/fabric/tls
        - peer0.city2.zak.codes:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053

  peer1.city2.zak.codes:
    container_name: peer1.city2.zak.codes
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.city2.zak.codes
      - CORE_PEER_ADDRESS=peer1.city2.zak.codes:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.city2.zak.codes:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.city2.zak.codes:7051
      - CORE_PEER_LOCALMSPID=City2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/city2.zak.codes/peers/peer1.city2.zak.codes/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/city2.zak.codes/peers/peer1.city2.zak.codes/tls:/etc/hyperledger/fabric/tls
        - peer1.city2.zak.codes:/var/hyperledger/production
    ports:
      - 10051:7051
      - 10053:7053
